site_name: GraphMk 0.1
site_url: https://github.com/graphmk/py-graphmk
site_description: Python GraphMk Documentation

repo_url: https://github.com/graphmk/py-graphmk

docs_dir: docs

pages:
- Home: 'index.md'
- FAQ: 'faq.md'
- Contact Us: 'contact-us.md'

theme: readthedocs

markdown_extensions:
  - toc:
     permalink: 
  - admonition
